strictness: veryhigh
doc-warnings: true
member-warnings: false
test-warnings: false

ignore-patterns:
  - (^|/)\..+
  - .*\.html
  - docs/.*
  - extra/.*
  - tmp\.py

pylint:
  disable:
    - bad-continuation
    - broad-except
    - import-error
    - import-self
    - logging-format-interpolation
    - missing-docstring
    - no-self-use
    - unused-argument
    - wrong-import-order
    - unsubscriptable-object

  options:
    max-args: 20
    max-locals: 100
    max-returns: 10
    max-branches: 50
    max-statements: 180
    max-parents: 10
    max-attributes: 22
    min-public-methods: 0
    max-public-methods: 20
    max-module-lines: 2000
    max-line-length: 100

mccabe:
  options:
    max-complexity: 30

pycodestyle:
  disable:
    - N802
    - N807
    - W503
    - E203
  options:
    max-line-length: 100
    single-line-if-stmt: n

vulture:
  run: false

pyroma:
  run: false
  disable:
    - PYR19
    - PYR16

pydocstyle:
  disable:
    - D000
    - D100
    - D101
    - D102
    - D103
    - D104
    - D105
    - D107
    - D200
    - D202
    - D203
    - D205
    - D212
    - D204
    - D300
    - D301
    - D400
    - D401
    - D404
    - D403
    - D415
